### PR TITLE
Add pause test for every pasuable function

### PR DESCRIPTION
**Pull request by libertylocked**
- no records can be added or attested when records contract is paused
- whenNotPaused tests moved to affected methods in tests

### CODE REVIEW

**Comment by libertylocked** [comment]
fixes #51 maybe

**Comment by MaxBlaushild** [comment]
Do we get any new functionality here? Or do we fix any bug?

**Comment by libertylocked** [comment]
Better coverage

**Comment by godfreyhobbs** [comment]
consider leaving whenNotPaused where is already exists.

Adding whenNotPaused to the internal method is not a problem. But I do not like removing whenNotPaused from the external/public methods.  I would rather have the whenNotPaused as part of the public/external function signature.  This is a way of self-documenting the code.

**Comment by godfreyhobbs** [comment]
Also do you know why test coverge has not increased? 
` Coverage   96.52%   96.52%`

**Comment by libertylocked** [comment]
line coverage doesn't change

**Comment by godfreyhobbs** [comment]
The branch coverage is unchanged at `25`

  Branches       25       25  

Does our coverage tool not work?

**Pull request closed without merging**
