### PR TITLE
Linnia architecture diagram added; README.md updated with the diagram

### PR DESCRIPTION
**Pull request by leeb2018**
Quick update to README.md after adding the Linnia architecture diagram.

### CODE REVIEW

**Comment by godfreyhobbs** [comment]
@leeb2018 It does not make sense to share with a Nonuser.  Consider removing the Non-user.

**Comment by vrotmanh** [comment]
Good Diagram. I only don't like the text in the orange box of the permissions contract. That text is a little confusing

It can be something like the LinniaUsers can manage who have access to their data. Maybe something like LinniaUsers can grant and revoke access.
The nonzero ethereum address sounds confusing too

Otherwise great job!

**Comment by leeb2018** [comment]
@godfreyhobbs Ah, I missed the "onlyUser" modifier. I will remove "Nonuser".

@vrotmanh Thank you for your feedback! It was really helpful. I have made an update accordingly.

You can check out the updated version of the diagram [here](https://docs.google.com/drawings/d/1QPVkL3CoUjc-2taowtyY_6KwTMu8pNY-R2bAo626Bdo/edit?usp=sharing). Let me know what you think! Love to hear more feedbacks.

**Comment by davidrhodus** [comment]
@leeb2018 can you update the pull request with the updated diagram?

**Comment by leeb2018** [comment]
Issue with signing commit got out of my hand, so I have decided to close this PR and delete branch. I will create exact same branch and PR with updated diagram.

**Pull request closed without merging**
