### PR TITLE
dataUri as string rather than byte32.  This allow longer data URI inc…

### PR DESCRIPTION
**Pull request by godfreyhobbs**
…luding popular cloud based data Uris

### CODE REVIEW

**Comment by libertylocked** [comment]
what is the URI schema?

**Comment by libertylocked** [comment]
How are the data URI computed? How are they resolved? For instance, what makes an IPFS URI different than an HTTP URI? What are the other possible protocols? Why `string` not `bytes`? Will this break IPFS URIs? Currently the URI are IPFS paths which is exactly 32bytes, but aren't printable ASCII. If they are stored in `string`, they will be 33 bytes (incl. NUL), which is 2 words.

**Comment by libertylocked** [comment]
assertRevert does not catch out of gas.

**Comment by godfreyhobbs** [comment]
If the test runs out of gas they should fail.  assertRevert ensures this failure.  expectThrow is too broad.

**Comment by godfreyhobbs** [comment]
Fixes #40

**Pull request merged**
